### ISSUE TITLE
404 - it's wrong.

### ISSUE THREAD

**Issue by sea-kg** [freehackquest/backend#40]
Sended: {"parentid":3,"search":"","cmd":"classbook_list","m":"m7"}
Response: {"cmd":"classbook_list","code":404,"error":"Not found the article with a given parentid","m":"m7","result":"FAIL"}

Article 3 exists, but list returned with 404 - it's wrong.
404 must be returned if article with classbookid (==parent) not exists.

**Comment by sea-kg** [comment]
Wrong here must check that classbookid exists

    // CHECK exist parentid in DB
    query.prepare("SELECT name FROM classbook WHERE parentid =:parentid");
    query.bindValue(":parentid", parentid);
    query.exec();
    if (!query.next() && parentid != 0){
        pWebSocketServer->sendMessageError(pClient, cmd(), m, Error(404, "Not found the article with a given parentid"));
        return;
    }

**Comment by I0x4dI** [comment]
Fixed
