### ISSUE TITLE
Error in handler leaks_list

### ISSUE THREAD

**Issue by sea-kg** [freehackquest/backend#96]
if user is not admin: user could not set filter 'search' by field 'message', just change search by name - it will be enough. So... we have not field 'message' only name and content in table leaks

**Comment by KeimaShikai** [comment]
I found the problem with a 'message' field and fixed it. My bad. But how should I handle my first mistake? Do I need to expel this part with setting filter by 'content' at all? Or we need to check somehow our user's status inside the handler one more time and if it's an admin - let him add his filter by 'content'?

**Comment by sea-kg** [comment]
Yes you can check who make request to this handler admin or user.
If user is "admin" include filter else not include filter.
